### PR TITLE
Open Weather API changes, and fixes for new data signature

### PR DESCRIPTION
**Pull request by brianespinosa**
This PR fixes the broken API call now that the 16 day forecast is no longer free. Additionally, this also adds new weather codes and times to the forecast since the 5 day forecast slightly different.

### CODE REVIEW

**Comment by brianespinosa** [comment]
This resolves #17

**Review by jeremykenedy — APPROVED** [review]

**Comment by jeremykenedy** [comment]
I have confirmed these changes will fix the package to run out the box. These should be merged in.
Thank you,
Jeremy

**Comment by jeremykenedy** [comment]
@plouc Is this repository no longer maintained?

**Comment by brianespinosa** [comment]
I am going to go ahead and decline this PR. Looks like it will never go in and it has been sitting on my PRs list for a year and a half. If anyone else comes along and would like to take this back up, please feel free to use this update.

CI builds never worked due to missing environment variables during build, so the issue with builds not passing it seems exists somewhere in the CI configuration.

**Pull request closed without merging**
